
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.197.98:3306/shrek_guid?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: Ali@2020
server:
  port: 8888